apiVersion: v1
kind: Service
metadata:
  name: service-server
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: {{ .Values.server.port }}
      targetPort: {{ .Values.server.port }}
