apiVersion: v1
kind: Service
metadata:
  name: service-client
spec:
  selector:
    app: client
  type: NodePort
  ports:
    - protocol: TCP
      port: {{ .Values.client.port }}
      targetPort: {{ .Values.client.port }}
